### ISSUE TITLE
The time of talks is incorrect

### ISSUE THREAD

**Issue by StephaneColson** [mixitconf/mixit-android#9]
My smartphone is configured with french timezone (GMT+2) and schedule time is incorrect, displayed with an additional 2 hours.

For example, see this screenshot:

![screenshot_20180416-173349](https://user-images.githubusercontent.com/1481595/38819940-02a18e00-419d-11e8-99fa-e88517d1a2c7.png)

"Punishment and Humiliation" is scheduled for starting at 12h10, but the correct starting time is 10h10.

The correct time is displayed if I'm switching to GMT timezone on my smartphone.

**Comment by javamind** [comment]
Thanks for your issue

**Comment by StephaneColson** [comment]
It works, thanks
